server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://identity-service:8083
          predicates:
            - Path=/auth/**

        - id: account-service
          uri: http://account-service:8080
          predicates:
            - Path=/api/v1/accounts/**,/api/v1/transfers/**

        - id: fraud-service
          uri: http://fraud-service:8082
          predicates:
            - Path=/api/v1/fraud/**,/api/v1/loans/**,/api/v1/anomalies/**,/api/v1/agent/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.gateway: INFO